### ISSUE TITLE
unable to find interfaces, localplayerptr and convar vftable

### ISSUE THREAD

**Issue by louis-dnb** [CasualX/apexbot#21]
Game is dumped with scylla,
Trying to get Offsets gives the following error:

`unable to find any interfaces!
unable to find LocalPlayerPtr!
ERR: unable to find ConVar vftable`

https://i.imgur.com/Y7ofGpc.png

**Comment by CasualX** [comment]
The offset dumper has been updated, interfaces are no longer available though.
