### ISSUE TITLE
Help implementing bypass into cheat

### ISSUE THREAD

**Issue by n7ll** [CasualX/apexbot#22]
I have a kernel driver, but I'm confused. I'm not sure how to pair it within the bypass section. There are memory functions within it listed in the directions but it's composed of multiple C++ files and I'm confused as to whether I should just paste all of them raw in the bypass section or what. My discord is Nax#4661 if anyone can help.

**Comment by CasualX** [comment]
This is not the right place to ask for help, sorry.
