### ISSUE TITLE
cargo build fail

### ISSUE THREAD

**Issue by 04255** [CasualX/apexbot#24]
cmd offsets cargo build
`error: failed to download `fmtools v0.1.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\fmtools-0.1.0\Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature`

**Comment by 04255** [comment]
i'm new to RUST, i want to build .exe,
After update i cant cargo build, can you help me?

**Comment by CasualX** [comment]
Update your Rust toolchain: rustup update

Your version of Rust is out of date, simply updating it will make it build.
