### ISSUE TITLE
Needs help about bypass 

### ISSUE THREAD

**Issue by AtomBottle** [CasualX/apexbot#31]
hi,
i found a repo:
https://github.com/SamuelTulach/efi-memory/
and,  seem EAC doesn't detect EFI driver .....
but , how can i use it to bypass EAC, I am not good at coding. Can you give me some advice?
Thanks a lot

**Comment by CasualX** [comment]
Hi, apexbot does not include any specific EAC bypass and I cannot help you with implementing one, sorry.
