### ISSUE TITLE
What's wrong with this?

### ISSUE THREAD

**Issue by ironman97** [CasualX/apexbot#34]
![错误截图](https://user-images.githubusercontent.com/38624406/213980651-333048bc-1da0-478f-9d79-42f560f962a0.png)

How to solve this problem?

If you can reply to me, I will be very grateful!

**Comment by CasualX** [comment]
This may be a problem with older versions, after a ` cargo update` try again?

**Comment by ironman97** [comment]
我使用了最新版的cargo，但是问题还是没有得到解决。我不得不使用网页APP来分析我的.bin文件。  我发现我的.bin文件里没有 “LocalPlayer”，这个是哪步操作不对吗？

**Comment by ironman97** [comment]
I used the latest version of cargo, but the problem has not been solved. I have to use web app to analyze my. bin file. I found that there is no "LocalPlayer" in my. bin file. What is wrong with this operation?

**Comment by ironman97** [comment]
![QQ截图20230125223024](https://user-images.githubusercontent.com/38624406/214590135-a1793aac-f032-4700-8830-929f27672d29.png)

**Comment by CasualX** [comment]
LocalPlayer can be found at `.?AVC_GameMovement@@ + 8`. In the past there was a direct reference to this value which was easily scannable. This is no longer the case (I can't find it) so the value is currently left out. At some future moment I'll fix this, but for now just know that LocalPlayer is the first field (after the vtable) of the global C_GameMovement instance.

As for the Rust error, I'm not getting this error. I can make the error appear by changing the `dataview` dependency to `1.0` (it should be `0.1` in Cargo.toml) or changing `pelite` to `0.10` (it's a git dependency). Something appears to go wrong there. I'll fix it by updating both to use the latest crates io release.

**Comment by ironman97** [comment]
Thank you very much for your answer！
