### ISSUE TITLE
Isnt the bypass already there?

### ISSUE THREAD

**Issue by CloakAndDagger-sys** [CasualX/apexbot#5]
// EAC BYPASS GOES HERE

bool read_process_memory(uint32_t pid, uint64_t address, void* buffer, size_t size) {
	return false;
}
bool write_process_memory(uint32_t pid, uint64_t address, const void* buffer, size_t size) {
	return false;
}
bool virtual_query_ex(uint32_t pid, uint64_t address, MEMORY_BASIC_INFORMATION& mbi) {
	return false;
}
const wchar_t* get_mapped_file_name(uint32_t pid, uint64_t address, void* buffer, size_t size) {
	return nullptr;
}

**Comment by CasualX** [comment]
These functions always fail; you must provide an appropriate implementation which works with EAC running.
