### ISSUE TITLE
dumper is broken

### ISSUE THREAD

**Issue by Noosb12345** [CasualX/apexbot#63]
> Waiting for an input file.
> Loaded apexdumper.wasm!
> Loading start_protected_game_dump.exe... ok!
> Dumping offsets...
! unable to find any interfaces!
! unable to find GameVersion!
! unable to find LocalEntityHandle!
! unable to find LocalPlayerPtr!
! unable to find NameList!
! unable to find ViewRender
! unable to find ClientState
! unable to find CPlayer lastVisibleTime offsets
! unable to find CWeaponX m_flProjectileSpeed offsets
! unable to find CPlayer camera offsets
! unable to find studio hdr
! unable to find NetworkVarTableLen
! unable to find modifiers
! ERR: unable to find WeaponSettings pattern ok!

**Comment by CasualX** [comment]
I no longer play apex, someone has to fix it and send in a PR and I'll accept it.
