### ISSUE TITLE
FOV checking seems to be broken at longer distances

### ISSUE THREAD

**Issue by bugproof** [CasualX/apexbot#9]
^ when you use a really low FOV like 1-2 it gets much bigger with distance, it should also use distance. https://www.unknowncheats.me/forum/c-and-c/114805-real-aimbot-crosshair-distance.html , or convert to screen coords and compare screen distance.

https://github.com/CasualX/apexbot/blob/master/src/aimassist.cpp#L142

**Comment by PythonRat** [comment]
hi dose this offset updated every time and tell how to find entity list on ida 
#define OFFSET_ENTITYLIST	
#define OFFSET_LOCAL			
#define OFFSET_LOCAL_ENT
how to see this offset on ida what thing i can type
